#!/usr/bin/env bash
# sync-global-brain.sh — propagate a curated cross-project "global brain" into each
# project's memory dir, so every cwd-scoped agent session surfaces the same universal
# operating lessons. Methodology: ../docs/global-brain.md
#
# This is a SANITIZED SKELETON. Adapt the CONFIG block to your setup. It ships nothing
# project-specific; the canonical set, the manifest, and the denylist are yours to fill.
#
# Design (see docs/global-brain.md):
#   - canonical global set  -> a manifest allowlist -> copied into each project's _global/
#   - generated + read-only inside projects (never hand-edit the copies)
#   - each _global/ is regenerated atomically (stage -> validate -> swap), never delete-first
#   - each project's MEMORY.md links to _global/INDEX.md (it does not duplicate it)
#   - --check detects drift; a denylist scan refuses to propagate secrets/PII
#
# Usage:
#   sync-global-brain.sh [--dry-run|--check] [project ...]   # no project args = all
#
# Exit codes: 0 ok · 1 usage · 2 not-found · 5 denylist hit (refused) · 6 drift (--check)

set -euo pipefail

# ----------------------------- CONFIG (edit me) ------------------------------
# Canonical home of the curated global set (one curated copy, edited only here):
CANONICAL="${GLOBAL_BRAIN_HOME:-$HOME/path/to/meta-workspace/brain/global}"
# Allowlist of files that propagate (one filename per line; '#' comments ok):
MANIFEST="$CANONICAL/global-brain.manifest"
# Projects to sync into. Each maps a label to that project's memory dir:
project_dir() {
  case "$1" in
    project-a) echo "$HOME/path/to/projects/project-a/memory" ;;
    project-b) echo "$HOME/path/to/projects/project-b/memory" ;;
    project-c) echo "$HOME/path/to/projects/project-c/memory" ;;
    *) return 1 ;;
  esac
}
ALL_PROJECTS="project-a project-b project-c"
# Denylist: regexes that must NEVER appear in a propagated memory (secrets/PII).
# Fill with your real patterns. A match aborts the sync (fail-closed).
DENYLIST='(-----BEGIN [A-Z ]*PRIVATE KEY-----|api[_-]?key|secret|token|password|/Users/[a-z]|/home/[a-z]|@[A-Za-z0-9._-]+\.[A-Za-z]{2,})'
# -----------------------------------------------------------------------------

MODE=apply; PROJECTS=""
usage() {
  cat <<'EOF'
sync-global-brain.sh — propagate a curated cross-project "global brain" into project memory dirs.

Usage:
  sync-global-brain.sh [--dry-run|--check] [project ...]

Modes:
  --dry-run   Show what would sync without writing.
  --check     Detect drift between canonical global memory and generated copies.
  -h, --help  Show this help.

Exit codes: 0 ok · 1 usage · 2 not-found · 5 denylist hit · 6 drift
EOF
}

for a in "$@"; do
  case "$a" in
    --dry-run) MODE=dry ;;
    --check)   MODE=check ;;
    -h|--help) usage; exit 0 ;;
    --*) echo "usage: unknown flag $a" >&2; exit 1 ;;
    *) PROJECTS="$PROJECTS $a" ;;
  esac
done
[ -z "${PROJECTS// }" ] && PROJECTS="$ALL_PROJECTS"
[ -f "$MANIFEST" ] || { echo "manifest not found: $MANIFEST" >&2; exit 2; }

# Read manifest -> FILES (strip comments/blanks); bash-3.2 safe.
FILES=()
while IFS= read -r line; do [ -n "$line" ] && FILES+=("$line"); done \
  < <(grep -vE '^[[:space:]]*#|^[[:space:]]*$' "$MANIFEST")

# Safety gate: refuse to propagate anything matching the denylist.
deny_scan() {
  local hit=0 f
  for f in "${FILES[@]}"; do
    [ -f "$CANONICAL/$f" ] || continue
    if grep -nEi "$DENYLIST" "$CANONICAL/$f" >/dev/null 2>&1; then
      echo "DENYLIST HIT in $f — refusing to sync (scrub canonical first)" >&2; hit=1
    fi
  done
  return $hit
}

desc() { awk 'NR==1&&$0!="---"{exit} /^description:/{sub(/^description:[ ]*/,"");print;exit}' "$1" 2>/dev/null; }
title() { awk -F': ' '/^name:/{print $2;exit}' "$1" 2>/dev/null || basename "$1" .md; }

# Drift check needs no writes and no denylist gate.
if [ "$MODE" = check ]; then
  drift=0
  for p in $PROJECTS; do
    d=$(project_dir "$p") || { echo "unknown project: $p" >&2; exit 2; }
    for f in "${FILES[@]}"; do
      diff -q "$CANONICAL/$f" "$d/_global/$f" >/dev/null 2>&1 || { echo "DRIFT [$p]: $f"; drift=1; }
    done
  done
  [ "$drift" -eq 0 ] && { echo "global brain: in sync"; exit 0; } || exit 6
fi

# Apply / dry-run both run the denylist gate first (fail-closed).
deny_scan || exit 5

BANNER='<!-- GENERATED by sync-global-brain.sh — do not edit. Edit the canonical global set, then re-run sync. -->'

for p in $PROJECTS; do
  d=$(project_dir "$p") || { echo "unknown project: $p" >&2; exit 2; }
  g="$d/_global"
  if [ "$MODE" = dry ]; then
    echo "[$p] would sync ${#FILES[@]} files -> $g/ ; rebuild INDEX.md + MEMORY.md link section"; continue
  fi
  # Staged regen: stage in a temp dir on the SAME filesystem, validate, then rename-swap.
  # Never delete-first — a failure leaves the existing _global/ untouched (brief absent
  # window between the two renames, but never a partially-populated _global/).
  mkdir -p "$d"
  rm -rf "$d"/.global-stage.* "$d"/.global-old.* 2>/dev/null || true   # clear prior-run orphans
  stage=$(mktemp -d "$d/.global-stage.XXXXXX") || { echo "ERROR: cannot create staging dir in $d" >&2; exit 1; }
  copied=0
  for f in "${FILES[@]}"; do
    if [ -f "$CANONICAL/$f" ]; then cp "$CANONICAL/$f" "$stage/$f"; copied=$((copied+1));
    else echo "WARN missing canonical: $f" >&2; fi
  done
  # Staged generated index.
  { echo "# Global Brain — generated index"; echo ""; echo "$BANNER"; echo "";
    for f in "${FILES[@]}"; do [ -f "$stage/$f" ] && echo "- [$(title "$stage/$f")]($f) — $(desc "$stage/$f")"; done
  } > "$stage/INDEX.md"
  # Validate the staged tree BEFORE touching the live _global/.
  if [ "$copied" -eq 0 ] || [ ! -s "$stage/INDEX.md" ]; then
    echo "ERROR [$p]: staged _global/ invalid (copied=$copied) — existing _global/ left untouched." >&2
    rm -rf "$stage"; exit 1
  fi
  # Atomic swap: move old aside, move staged into place, drop old. No delete-first.
  old="$d/.global-old.$$"
  rm -rf "$old"
  [ -d "$g" ] && mv "$g" "$old"
  if ! mv "$stage" "$g"; then
    echo "ERROR [$p]: swap failed — restoring previous _global/." >&2
    [ -d "$old" ] && mv "$old" "$g"
    rm -rf "$stage"; exit 1
  fi
  rm -rf "$old"
  # Idempotent MEMORY.md link section (between markers); link, don't duplicate.
  mem="$d/MEMORY.md"; [ -f "$mem" ] || printf '# %s Memory Index\n' "$p" > "$mem"
  blk=$(mktemp)
  { echo "<!-- BEGIN GLOBAL BRAIN (generated) -->";
    echo "## Global Brain (cross-project — read \`_global/INDEX.md\` at session start)";
    echo "${#FILES[@]} universal lessons synced from the canonical set. Full list: [\`_global/INDEX.md\`](_global/INDEX.md). $BANNER";
    echo "<!-- END GLOBAL BRAIN -->"; } > "$blk"
  if grep -q 'BEGIN GLOBAL BRAIN' "$mem"; then
    awk -v bf="$blk" '/BEGIN GLOBAL BRAIN/{while((getline l<bf)>0)print l;s=1;next} s&&/END GLOBAL BRAIN/{s=0;next} !s{print}' "$mem" > "$mem.tmp" && mv "$mem.tmp" "$mem"
  else
    { head -1 "$mem"; echo ""; cat "$blk"; echo ""; tail -n +2 "$mem"; } > "$mem.tmp" && mv "$mem.tmp" "$mem"
  fi
  rm -f "$blk"
  echo "[$p] synced $copied/${#FILES[@]} files -> $g/ (atomic)"
done
exit 0
